services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # This was missing/misconfigured
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"  # This was missing/misconfigured
    depends_on:
      - backend
